// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"windwalker/ent/collegeprofile"
	"windwalker/ent/predicate"
	"windwalker/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rs/xid"
)

// CollegeProfileUpdate is the builder for updating CollegeProfile entities.
type CollegeProfileUpdate struct {
	config
	hooks    []Hook
	mutation *CollegeProfileMutation
}

// Where appends a list predicates to the CollegeProfileUpdate builder.
func (cpu *CollegeProfileUpdate) Where(ps ...predicate.CollegeProfile) *CollegeProfileUpdate {
	cpu.mutation.Where(ps...)
	return cpu
}

// SetName sets the "name" field.
func (cpu *CollegeProfileUpdate) SetName(s string) *CollegeProfileUpdate {
	cpu.mutation.SetName(s)
	return cpu
}

// SetPhone sets the "phone" field.
func (cpu *CollegeProfileUpdate) SetPhone(s string) *CollegeProfileUpdate {
	cpu.mutation.SetPhone(s)
	return cpu
}

// SetAddress sets the "address" field.
func (cpu *CollegeProfileUpdate) SetAddress(s string) *CollegeProfileUpdate {
	cpu.mutation.SetAddress(s)
	return cpu
}

// SetType sets the "type" field.
func (cpu *CollegeProfileUpdate) SetType(s string) *CollegeProfileUpdate {
	cpu.mutation.SetType(s)
	return cpu
}

// SetUserID sets the "user" edge to the User entity by ID.
func (cpu *CollegeProfileUpdate) SetUserID(id xid.ID) *CollegeProfileUpdate {
	cpu.mutation.SetUserID(id)
	return cpu
}

// SetUser sets the "user" edge to the User entity.
func (cpu *CollegeProfileUpdate) SetUser(u *User) *CollegeProfileUpdate {
	return cpu.SetUserID(u.ID)
}

// Mutation returns the CollegeProfileMutation object of the builder.
func (cpu *CollegeProfileUpdate) Mutation() *CollegeProfileMutation {
	return cpu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (cpu *CollegeProfileUpdate) ClearUser() *CollegeProfileUpdate {
	cpu.mutation.ClearUser()
	return cpu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cpu *CollegeProfileUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cpu.hooks) == 0 {
		if err = cpu.check(); err != nil {
			return 0, err
		}
		affected, err = cpu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CollegeProfileMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cpu.check(); err != nil {
				return 0, err
			}
			cpu.mutation = mutation
			affected, err = cpu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cpu.hooks) - 1; i >= 0; i-- {
			if cpu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cpu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cpu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cpu *CollegeProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := cpu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cpu *CollegeProfileUpdate) Exec(ctx context.Context) error {
	_, err := cpu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cpu *CollegeProfileUpdate) ExecX(ctx context.Context) {
	if err := cpu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cpu *CollegeProfileUpdate) check() error {
	if v, ok := cpu.mutation.Name(); ok {
		if err := collegeprofile.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CollegeProfile.name": %w`, err)}
		}
	}
	if v, ok := cpu.mutation.Phone(); ok {
		if err := collegeprofile.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "CollegeProfile.phone": %w`, err)}
		}
	}
	if v, ok := cpu.mutation.Address(); ok {
		if err := collegeprofile.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "CollegeProfile.address": %w`, err)}
		}
	}
	if v, ok := cpu.mutation.GetType(); ok {
		if err := collegeprofile.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "CollegeProfile.type": %w`, err)}
		}
	}
	if _, ok := cpu.mutation.UserID(); cpu.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "CollegeProfile.user"`)
	}
	return nil
}

func (cpu *CollegeProfileUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   collegeprofile.Table,
			Columns: collegeprofile.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: collegeprofile.FieldID,
			},
		},
	}
	if ps := cpu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cpu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: collegeprofile.FieldName,
		})
	}
	if value, ok := cpu.mutation.Phone(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: collegeprofile.FieldPhone,
		})
	}
	if value, ok := cpu.mutation.Address(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: collegeprofile.FieldAddress,
		})
	}
	if value, ok := cpu.mutation.GetType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: collegeprofile.FieldType,
		})
	}
	if cpu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   collegeprofile.UserTable,
			Columns: []string{collegeprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cpu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   collegeprofile.UserTable,
			Columns: []string{collegeprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cpu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{collegeprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// CollegeProfileUpdateOne is the builder for updating a single CollegeProfile entity.
type CollegeProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CollegeProfileMutation
}

// SetName sets the "name" field.
func (cpuo *CollegeProfileUpdateOne) SetName(s string) *CollegeProfileUpdateOne {
	cpuo.mutation.SetName(s)
	return cpuo
}

// SetPhone sets the "phone" field.
func (cpuo *CollegeProfileUpdateOne) SetPhone(s string) *CollegeProfileUpdateOne {
	cpuo.mutation.SetPhone(s)
	return cpuo
}

// SetAddress sets the "address" field.
func (cpuo *CollegeProfileUpdateOne) SetAddress(s string) *CollegeProfileUpdateOne {
	cpuo.mutation.SetAddress(s)
	return cpuo
}

// SetType sets the "type" field.
func (cpuo *CollegeProfileUpdateOne) SetType(s string) *CollegeProfileUpdateOne {
	cpuo.mutation.SetType(s)
	return cpuo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (cpuo *CollegeProfileUpdateOne) SetUserID(id xid.ID) *CollegeProfileUpdateOne {
	cpuo.mutation.SetUserID(id)
	return cpuo
}

// SetUser sets the "user" edge to the User entity.
func (cpuo *CollegeProfileUpdateOne) SetUser(u *User) *CollegeProfileUpdateOne {
	return cpuo.SetUserID(u.ID)
}

// Mutation returns the CollegeProfileMutation object of the builder.
func (cpuo *CollegeProfileUpdateOne) Mutation() *CollegeProfileMutation {
	return cpuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (cpuo *CollegeProfileUpdateOne) ClearUser() *CollegeProfileUpdateOne {
	cpuo.mutation.ClearUser()
	return cpuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cpuo *CollegeProfileUpdateOne) Select(field string, fields ...string) *CollegeProfileUpdateOne {
	cpuo.fields = append([]string{field}, fields...)
	return cpuo
}

// Save executes the query and returns the updated CollegeProfile entity.
func (cpuo *CollegeProfileUpdateOne) Save(ctx context.Context) (*CollegeProfile, error) {
	var (
		err  error
		node *CollegeProfile
	)
	if len(cpuo.hooks) == 0 {
		if err = cpuo.check(); err != nil {
			return nil, err
		}
		node, err = cpuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CollegeProfileMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cpuo.check(); err != nil {
				return nil, err
			}
			cpuo.mutation = mutation
			node, err = cpuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cpuo.hooks) - 1; i >= 0; i-- {
			if cpuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cpuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cpuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cpuo *CollegeProfileUpdateOne) SaveX(ctx context.Context) *CollegeProfile {
	node, err := cpuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cpuo *CollegeProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := cpuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cpuo *CollegeProfileUpdateOne) ExecX(ctx context.Context) {
	if err := cpuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cpuo *CollegeProfileUpdateOne) check() error {
	if v, ok := cpuo.mutation.Name(); ok {
		if err := collegeprofile.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CollegeProfile.name": %w`, err)}
		}
	}
	if v, ok := cpuo.mutation.Phone(); ok {
		if err := collegeprofile.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "CollegeProfile.phone": %w`, err)}
		}
	}
	if v, ok := cpuo.mutation.Address(); ok {
		if err := collegeprofile.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "CollegeProfile.address": %w`, err)}
		}
	}
	if v, ok := cpuo.mutation.GetType(); ok {
		if err := collegeprofile.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "CollegeProfile.type": %w`, err)}
		}
	}
	if _, ok := cpuo.mutation.UserID(); cpuo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "CollegeProfile.user"`)
	}
	return nil
}

func (cpuo *CollegeProfileUpdateOne) sqlSave(ctx context.Context) (_node *CollegeProfile, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   collegeprofile.Table,
			Columns: collegeprofile.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: collegeprofile.FieldID,
			},
		},
	}
	id, ok := cpuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CollegeProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cpuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, collegeprofile.FieldID)
		for _, f := range fields {
			if !collegeprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != collegeprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cpuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cpuo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: collegeprofile.FieldName,
		})
	}
	if value, ok := cpuo.mutation.Phone(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: collegeprofile.FieldPhone,
		})
	}
	if value, ok := cpuo.mutation.Address(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: collegeprofile.FieldAddress,
		})
	}
	if value, ok := cpuo.mutation.GetType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: collegeprofile.FieldType,
		})
	}
	if cpuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   collegeprofile.UserTable,
			Columns: []string{collegeprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cpuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   collegeprofile.UserTable,
			Columns: []string{collegeprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CollegeProfile{config: cpuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cpuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{collegeprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
