// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"
	"windwalker/ent/company"
	"windwalker/ent/jobpost"
	"windwalker/ent/predicate"
	"windwalker/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rs/xid"
)

// JobPostQuery is the builder for querying JobPost entities.
type JobPostQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.JobPost
	// eager-loading edges.
	withUser       *UserQuery
	withCompany    *CompanyQuery
	withCandidates *UserQuery
	withFKs        bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the JobPostQuery builder.
func (jpq *JobPostQuery) Where(ps ...predicate.JobPost) *JobPostQuery {
	jpq.predicates = append(jpq.predicates, ps...)
	return jpq
}

// Limit adds a limit step to the query.
func (jpq *JobPostQuery) Limit(limit int) *JobPostQuery {
	jpq.limit = &limit
	return jpq
}

// Offset adds an offset step to the query.
func (jpq *JobPostQuery) Offset(offset int) *JobPostQuery {
	jpq.offset = &offset
	return jpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (jpq *JobPostQuery) Unique(unique bool) *JobPostQuery {
	jpq.unique = &unique
	return jpq
}

// Order adds an order step to the query.
func (jpq *JobPostQuery) Order(o ...OrderFunc) *JobPostQuery {
	jpq.order = append(jpq.order, o...)
	return jpq
}

// QueryUser chains the current query on the "user" edge.
func (jpq *JobPostQuery) QueryUser() *UserQuery {
	query := &UserQuery{config: jpq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := jpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := jpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(jobpost.Table, jobpost.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, jobpost.UserTable, jobpost.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(jpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCompany chains the current query on the "company" edge.
func (jpq *JobPostQuery) QueryCompany() *CompanyQuery {
	query := &CompanyQuery{config: jpq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := jpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := jpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(jobpost.Table, jobpost.FieldID, selector),
			sqlgraph.To(company.Table, company.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, jobpost.CompanyTable, jobpost.CompanyColumn),
		)
		fromU = sqlgraph.SetNeighbors(jpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCandidates chains the current query on the "candidates" edge.
func (jpq *JobPostQuery) QueryCandidates() *UserQuery {
	query := &UserQuery{config: jpq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := jpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := jpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(jobpost.Table, jobpost.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, jobpost.CandidatesTable, jobpost.CandidatesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(jpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first JobPost entity from the query.
// Returns a *NotFoundError when no JobPost was found.
func (jpq *JobPostQuery) First(ctx context.Context) (*JobPost, error) {
	nodes, err := jpq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{jobpost.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (jpq *JobPostQuery) FirstX(ctx context.Context) *JobPost {
	node, err := jpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first JobPost ID from the query.
// Returns a *NotFoundError when no JobPost ID was found.
func (jpq *JobPostQuery) FirstID(ctx context.Context) (id xid.ID, err error) {
	var ids []xid.ID
	if ids, err = jpq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{jobpost.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (jpq *JobPostQuery) FirstIDX(ctx context.Context) xid.ID {
	id, err := jpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single JobPost entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one JobPost entity is found.
// Returns a *NotFoundError when no JobPost entities are found.
func (jpq *JobPostQuery) Only(ctx context.Context) (*JobPost, error) {
	nodes, err := jpq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{jobpost.Label}
	default:
		return nil, &NotSingularError{jobpost.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (jpq *JobPostQuery) OnlyX(ctx context.Context) *JobPost {
	node, err := jpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only JobPost ID in the query.
// Returns a *NotSingularError when more than one JobPost ID is found.
// Returns a *NotFoundError when no entities are found.
func (jpq *JobPostQuery) OnlyID(ctx context.Context) (id xid.ID, err error) {
	var ids []xid.ID
	if ids, err = jpq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{jobpost.Label}
	default:
		err = &NotSingularError{jobpost.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (jpq *JobPostQuery) OnlyIDX(ctx context.Context) xid.ID {
	id, err := jpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of JobPosts.
func (jpq *JobPostQuery) All(ctx context.Context) ([]*JobPost, error) {
	if err := jpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return jpq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (jpq *JobPostQuery) AllX(ctx context.Context) []*JobPost {
	nodes, err := jpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of JobPost IDs.
func (jpq *JobPostQuery) IDs(ctx context.Context) ([]xid.ID, error) {
	var ids []xid.ID
	if err := jpq.Select(jobpost.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (jpq *JobPostQuery) IDsX(ctx context.Context) []xid.ID {
	ids, err := jpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (jpq *JobPostQuery) Count(ctx context.Context) (int, error) {
	if err := jpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return jpq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (jpq *JobPostQuery) CountX(ctx context.Context) int {
	count, err := jpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (jpq *JobPostQuery) Exist(ctx context.Context) (bool, error) {
	if err := jpq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return jpq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (jpq *JobPostQuery) ExistX(ctx context.Context) bool {
	exist, err := jpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the JobPostQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (jpq *JobPostQuery) Clone() *JobPostQuery {
	if jpq == nil {
		return nil
	}
	return &JobPostQuery{
		config:         jpq.config,
		limit:          jpq.limit,
		offset:         jpq.offset,
		order:          append([]OrderFunc{}, jpq.order...),
		predicates:     append([]predicate.JobPost{}, jpq.predicates...),
		withUser:       jpq.withUser.Clone(),
		withCompany:    jpq.withCompany.Clone(),
		withCandidates: jpq.withCandidates.Clone(),
		// clone intermediate query.
		sql:    jpq.sql.Clone(),
		path:   jpq.path,
		unique: jpq.unique,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (jpq *JobPostQuery) WithUser(opts ...func(*UserQuery)) *JobPostQuery {
	query := &UserQuery{config: jpq.config}
	for _, opt := range opts {
		opt(query)
	}
	jpq.withUser = query
	return jpq
}

// WithCompany tells the query-builder to eager-load the nodes that are connected to
// the "company" edge. The optional arguments are used to configure the query builder of the edge.
func (jpq *JobPostQuery) WithCompany(opts ...func(*CompanyQuery)) *JobPostQuery {
	query := &CompanyQuery{config: jpq.config}
	for _, opt := range opts {
		opt(query)
	}
	jpq.withCompany = query
	return jpq
}

// WithCandidates tells the query-builder to eager-load the nodes that are connected to
// the "candidates" edge. The optional arguments are used to configure the query builder of the edge.
func (jpq *JobPostQuery) WithCandidates(opts ...func(*UserQuery)) *JobPostQuery {
	query := &UserQuery{config: jpq.config}
	for _, opt := range opts {
		opt(query)
	}
	jpq.withCandidates = query
	return jpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Position string `json:"position,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.JobPost.Query().
//		GroupBy(jobpost.FieldPosition).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (jpq *JobPostQuery) GroupBy(field string, fields ...string) *JobPostGroupBy {
	group := &JobPostGroupBy{config: jpq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := jpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return jpq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Position string `json:"position,omitempty"`
//	}
//
//	client.JobPost.Query().
//		Select(jobpost.FieldPosition).
//		Scan(ctx, &v)
//
func (jpq *JobPostQuery) Select(fields ...string) *JobPostSelect {
	jpq.fields = append(jpq.fields, fields...)
	return &JobPostSelect{JobPostQuery: jpq}
}

func (jpq *JobPostQuery) prepareQuery(ctx context.Context) error {
	for _, f := range jpq.fields {
		if !jobpost.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if jpq.path != nil {
		prev, err := jpq.path(ctx)
		if err != nil {
			return err
		}
		jpq.sql = prev
	}
	return nil
}

func (jpq *JobPostQuery) sqlAll(ctx context.Context) ([]*JobPost, error) {
	var (
		nodes       = []*JobPost{}
		withFKs     = jpq.withFKs
		_spec       = jpq.querySpec()
		loadedTypes = [3]bool{
			jpq.withUser != nil,
			jpq.withCompany != nil,
			jpq.withCandidates != nil,
		}
	)
	if jpq.withUser != nil || jpq.withCompany != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, jobpost.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &JobPost{config: jpq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, jpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := jpq.withUser; query != nil {
		ids := make([]xid.ID, 0, len(nodes))
		nodeids := make(map[xid.ID][]*JobPost)
		for i := range nodes {
			if nodes[i].user_job_posts == nil {
				continue
			}
			fk := *nodes[i].user_job_posts
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(user.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "user_job_posts" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.User = n
			}
		}
	}

	if query := jpq.withCompany; query != nil {
		ids := make([]xid.ID, 0, len(nodes))
		nodeids := make(map[xid.ID][]*JobPost)
		for i := range nodes {
			if nodes[i].company_posts == nil {
				continue
			}
			fk := *nodes[i].company_posts
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(company.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "company_posts" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Company = n
			}
		}
	}

	if query := jpq.withCandidates; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		ids := make(map[xid.ID]*JobPost, len(nodes))
		for _, node := range nodes {
			ids[node.ID] = node
			fks = append(fks, node.ID)
			node.Edges.Candidates = []*User{}
		}
		var (
			edgeids []xid.ID
			edges   = make(map[xid.ID][]*JobPost)
		)
		_spec := &sqlgraph.EdgeQuerySpec{
			Edge: &sqlgraph.EdgeSpec{
				Inverse: false,
				Table:   jobpost.CandidatesTable,
				Columns: jobpost.CandidatesPrimaryKey,
			},
			Predicate: func(s *sql.Selector) {
				s.Where(sql.InValues(jobpost.CandidatesPrimaryKey[0], fks...))
			},
			ScanValues: func() [2]interface{} {
				return [2]interface{}{new(xid.ID), new(xid.ID)}
			},
			Assign: func(out, in interface{}) error {
				eout, ok := out.(*xid.ID)
				if !ok || eout == nil {
					return fmt.Errorf("unexpected id value for edge-out")
				}
				ein, ok := in.(*xid.ID)
				if !ok || ein == nil {
					return fmt.Errorf("unexpected id value for edge-in")
				}
				outValue := *eout
				inValue := *ein
				node, ok := ids[outValue]
				if !ok {
					return fmt.Errorf("unexpected node id in edges: %v", outValue)
				}
				if _, ok := edges[inValue]; !ok {
					edgeids = append(edgeids, inValue)
				}
				edges[inValue] = append(edges[inValue], node)
				return nil
			},
		}
		if err := sqlgraph.QueryEdges(ctx, jpq.driver, _spec); err != nil {
			return nil, fmt.Errorf(`query edges "candidates": %w`, err)
		}
		query.Where(user.IDIn(edgeids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := edges[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected "candidates" node returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Candidates = append(nodes[i].Edges.Candidates, n)
			}
		}
	}

	return nodes, nil
}

func (jpq *JobPostQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := jpq.querySpec()
	_spec.Node.Columns = jpq.fields
	if len(jpq.fields) > 0 {
		_spec.Unique = jpq.unique != nil && *jpq.unique
	}
	return sqlgraph.CountNodes(ctx, jpq.driver, _spec)
}

func (jpq *JobPostQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := jpq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (jpq *JobPostQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   jobpost.Table,
			Columns: jobpost.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: jobpost.FieldID,
			},
		},
		From:   jpq.sql,
		Unique: true,
	}
	if unique := jpq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := jpq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, jobpost.FieldID)
		for i := range fields {
			if fields[i] != jobpost.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := jpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := jpq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := jpq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := jpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (jpq *JobPostQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(jpq.driver.Dialect())
	t1 := builder.Table(jobpost.Table)
	columns := jpq.fields
	if len(columns) == 0 {
		columns = jobpost.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if jpq.sql != nil {
		selector = jpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if jpq.unique != nil && *jpq.unique {
		selector.Distinct()
	}
	for _, p := range jpq.predicates {
		p(selector)
	}
	for _, p := range jpq.order {
		p(selector)
	}
	if offset := jpq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := jpq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// JobPostGroupBy is the group-by builder for JobPost entities.
type JobPostGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (jpgb *JobPostGroupBy) Aggregate(fns ...AggregateFunc) *JobPostGroupBy {
	jpgb.fns = append(jpgb.fns, fns...)
	return jpgb
}

// Scan applies the group-by query and scans the result into the given value.
func (jpgb *JobPostGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := jpgb.path(ctx)
	if err != nil {
		return err
	}
	jpgb.sql = query
	return jpgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (jpgb *JobPostGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := jpgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (jpgb *JobPostGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(jpgb.fields) > 1 {
		return nil, errors.New("ent: JobPostGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := jpgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (jpgb *JobPostGroupBy) StringsX(ctx context.Context) []string {
	v, err := jpgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (jpgb *JobPostGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = jpgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{jobpost.Label}
	default:
		err = fmt.Errorf("ent: JobPostGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (jpgb *JobPostGroupBy) StringX(ctx context.Context) string {
	v, err := jpgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (jpgb *JobPostGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(jpgb.fields) > 1 {
		return nil, errors.New("ent: JobPostGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := jpgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (jpgb *JobPostGroupBy) IntsX(ctx context.Context) []int {
	v, err := jpgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (jpgb *JobPostGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = jpgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{jobpost.Label}
	default:
		err = fmt.Errorf("ent: JobPostGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (jpgb *JobPostGroupBy) IntX(ctx context.Context) int {
	v, err := jpgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (jpgb *JobPostGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(jpgb.fields) > 1 {
		return nil, errors.New("ent: JobPostGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := jpgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (jpgb *JobPostGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := jpgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (jpgb *JobPostGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = jpgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{jobpost.Label}
	default:
		err = fmt.Errorf("ent: JobPostGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (jpgb *JobPostGroupBy) Float64X(ctx context.Context) float64 {
	v, err := jpgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (jpgb *JobPostGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(jpgb.fields) > 1 {
		return nil, errors.New("ent: JobPostGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := jpgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (jpgb *JobPostGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := jpgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (jpgb *JobPostGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = jpgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{jobpost.Label}
	default:
		err = fmt.Errorf("ent: JobPostGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (jpgb *JobPostGroupBy) BoolX(ctx context.Context) bool {
	v, err := jpgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (jpgb *JobPostGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range jpgb.fields {
		if !jobpost.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := jpgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := jpgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (jpgb *JobPostGroupBy) sqlQuery() *sql.Selector {
	selector := jpgb.sql.Select()
	aggregation := make([]string, 0, len(jpgb.fns))
	for _, fn := range jpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(jpgb.fields)+len(jpgb.fns))
		for _, f := range jpgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(jpgb.fields...)...)
}

// JobPostSelect is the builder for selecting fields of JobPost entities.
type JobPostSelect struct {
	*JobPostQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (jps *JobPostSelect) Scan(ctx context.Context, v interface{}) error {
	if err := jps.prepareQuery(ctx); err != nil {
		return err
	}
	jps.sql = jps.JobPostQuery.sqlQuery(ctx)
	return jps.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (jps *JobPostSelect) ScanX(ctx context.Context, v interface{}) {
	if err := jps.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (jps *JobPostSelect) Strings(ctx context.Context) ([]string, error) {
	if len(jps.fields) > 1 {
		return nil, errors.New("ent: JobPostSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := jps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (jps *JobPostSelect) StringsX(ctx context.Context) []string {
	v, err := jps.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (jps *JobPostSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = jps.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{jobpost.Label}
	default:
		err = fmt.Errorf("ent: JobPostSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (jps *JobPostSelect) StringX(ctx context.Context) string {
	v, err := jps.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (jps *JobPostSelect) Ints(ctx context.Context) ([]int, error) {
	if len(jps.fields) > 1 {
		return nil, errors.New("ent: JobPostSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := jps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (jps *JobPostSelect) IntsX(ctx context.Context) []int {
	v, err := jps.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (jps *JobPostSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = jps.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{jobpost.Label}
	default:
		err = fmt.Errorf("ent: JobPostSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (jps *JobPostSelect) IntX(ctx context.Context) int {
	v, err := jps.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (jps *JobPostSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(jps.fields) > 1 {
		return nil, errors.New("ent: JobPostSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := jps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (jps *JobPostSelect) Float64sX(ctx context.Context) []float64 {
	v, err := jps.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (jps *JobPostSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = jps.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{jobpost.Label}
	default:
		err = fmt.Errorf("ent: JobPostSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (jps *JobPostSelect) Float64X(ctx context.Context) float64 {
	v, err := jps.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (jps *JobPostSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(jps.fields) > 1 {
		return nil, errors.New("ent: JobPostSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := jps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (jps *JobPostSelect) BoolsX(ctx context.Context) []bool {
	v, err := jps.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (jps *JobPostSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = jps.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{jobpost.Label}
	default:
		err = fmt.Errorf("ent: JobPostSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (jps *JobPostSelect) BoolX(ctx context.Context) bool {
	v, err := jps.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (jps *JobPostSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := jps.sql.Query()
	if err := jps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
