// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"windwalker/ent/predicate"
	"windwalker/ent/studentacademicprofile"
	"windwalker/ent/studentprofile"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rs/xid"
)

// StudentAcademicProfileQuery is the builder for querying StudentAcademicProfile entities.
type StudentAcademicProfileQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.StudentAcademicProfile
	// eager-loading edges.
	withStudentProfile *StudentProfileQuery
	withFKs            bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StudentAcademicProfileQuery builder.
func (sapq *StudentAcademicProfileQuery) Where(ps ...predicate.StudentAcademicProfile) *StudentAcademicProfileQuery {
	sapq.predicates = append(sapq.predicates, ps...)
	return sapq
}

// Limit adds a limit step to the query.
func (sapq *StudentAcademicProfileQuery) Limit(limit int) *StudentAcademicProfileQuery {
	sapq.limit = &limit
	return sapq
}

// Offset adds an offset step to the query.
func (sapq *StudentAcademicProfileQuery) Offset(offset int) *StudentAcademicProfileQuery {
	sapq.offset = &offset
	return sapq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sapq *StudentAcademicProfileQuery) Unique(unique bool) *StudentAcademicProfileQuery {
	sapq.unique = &unique
	return sapq
}

// Order adds an order step to the query.
func (sapq *StudentAcademicProfileQuery) Order(o ...OrderFunc) *StudentAcademicProfileQuery {
	sapq.order = append(sapq.order, o...)
	return sapq
}

// QueryStudentProfile chains the current query on the "student_profile" edge.
func (sapq *StudentAcademicProfileQuery) QueryStudentProfile() *StudentProfileQuery {
	query := &StudentProfileQuery{config: sapq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sapq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sapq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(studentacademicprofile.Table, studentacademicprofile.FieldID, selector),
			sqlgraph.To(studentprofile.Table, studentprofile.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, studentacademicprofile.StudentProfileTable, studentacademicprofile.StudentProfileColumn),
		)
		fromU = sqlgraph.SetNeighbors(sapq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first StudentAcademicProfile entity from the query.
// Returns a *NotFoundError when no StudentAcademicProfile was found.
func (sapq *StudentAcademicProfileQuery) First(ctx context.Context) (*StudentAcademicProfile, error) {
	nodes, err := sapq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{studentacademicprofile.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sapq *StudentAcademicProfileQuery) FirstX(ctx context.Context) *StudentAcademicProfile {
	node, err := sapq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StudentAcademicProfile ID from the query.
// Returns a *NotFoundError when no StudentAcademicProfile ID was found.
func (sapq *StudentAcademicProfileQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = sapq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{studentacademicprofile.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sapq *StudentAcademicProfileQuery) FirstIDX(ctx context.Context) string {
	id, err := sapq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StudentAcademicProfile entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StudentAcademicProfile entity is found.
// Returns a *NotFoundError when no StudentAcademicProfile entities are found.
func (sapq *StudentAcademicProfileQuery) Only(ctx context.Context) (*StudentAcademicProfile, error) {
	nodes, err := sapq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{studentacademicprofile.Label}
	default:
		return nil, &NotSingularError{studentacademicprofile.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sapq *StudentAcademicProfileQuery) OnlyX(ctx context.Context) *StudentAcademicProfile {
	node, err := sapq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StudentAcademicProfile ID in the query.
// Returns a *NotSingularError when more than one StudentAcademicProfile ID is found.
// Returns a *NotFoundError when no entities are found.
func (sapq *StudentAcademicProfileQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = sapq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{studentacademicprofile.Label}
	default:
		err = &NotSingularError{studentacademicprofile.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sapq *StudentAcademicProfileQuery) OnlyIDX(ctx context.Context) string {
	id, err := sapq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StudentAcademicProfiles.
func (sapq *StudentAcademicProfileQuery) All(ctx context.Context) ([]*StudentAcademicProfile, error) {
	if err := sapq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return sapq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (sapq *StudentAcademicProfileQuery) AllX(ctx context.Context) []*StudentAcademicProfile {
	nodes, err := sapq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StudentAcademicProfile IDs.
func (sapq *StudentAcademicProfileQuery) IDs(ctx context.Context) ([]string, error) {
	var ids []string
	if err := sapq.Select(studentacademicprofile.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sapq *StudentAcademicProfileQuery) IDsX(ctx context.Context) []string {
	ids, err := sapq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sapq *StudentAcademicProfileQuery) Count(ctx context.Context) (int, error) {
	if err := sapq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return sapq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (sapq *StudentAcademicProfileQuery) CountX(ctx context.Context) int {
	count, err := sapq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sapq *StudentAcademicProfileQuery) Exist(ctx context.Context) (bool, error) {
	if err := sapq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return sapq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (sapq *StudentAcademicProfileQuery) ExistX(ctx context.Context) bool {
	exist, err := sapq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StudentAcademicProfileQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sapq *StudentAcademicProfileQuery) Clone() *StudentAcademicProfileQuery {
	if sapq == nil {
		return nil
	}
	return &StudentAcademicProfileQuery{
		config:             sapq.config,
		limit:              sapq.limit,
		offset:             sapq.offset,
		order:              append([]OrderFunc{}, sapq.order...),
		predicates:         append([]predicate.StudentAcademicProfile{}, sapq.predicates...),
		withStudentProfile: sapq.withStudentProfile.Clone(),
		// clone intermediate query.
		sql:    sapq.sql.Clone(),
		path:   sapq.path,
		unique: sapq.unique,
	}
}

// WithStudentProfile tells the query-builder to eager-load the nodes that are connected to
// the "student_profile" edge. The optional arguments are used to configure the query builder of the edge.
func (sapq *StudentAcademicProfileQuery) WithStudentProfile(opts ...func(*StudentProfileQuery)) *StudentAcademicProfileQuery {
	query := &StudentProfileQuery{config: sapq.config}
	for _, opt := range opts {
		opt(query)
	}
	sapq.withStudentProfile = query
	return sapq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Course string `json:"course,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StudentAcademicProfile.Query().
//		GroupBy(studentacademicprofile.FieldCourse).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (sapq *StudentAcademicProfileQuery) GroupBy(field string, fields ...string) *StudentAcademicProfileGroupBy {
	group := &StudentAcademicProfileGroupBy{config: sapq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := sapq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return sapq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Course string `json:"course,omitempty"`
//	}
//
//	client.StudentAcademicProfile.Query().
//		Select(studentacademicprofile.FieldCourse).
//		Scan(ctx, &v)
//
func (sapq *StudentAcademicProfileQuery) Select(fields ...string) *StudentAcademicProfileSelect {
	sapq.fields = append(sapq.fields, fields...)
	return &StudentAcademicProfileSelect{StudentAcademicProfileQuery: sapq}
}

func (sapq *StudentAcademicProfileQuery) prepareQuery(ctx context.Context) error {
	for _, f := range sapq.fields {
		if !studentacademicprofile.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sapq.path != nil {
		prev, err := sapq.path(ctx)
		if err != nil {
			return err
		}
		sapq.sql = prev
	}
	return nil
}

func (sapq *StudentAcademicProfileQuery) sqlAll(ctx context.Context) ([]*StudentAcademicProfile, error) {
	var (
		nodes       = []*StudentAcademicProfile{}
		withFKs     = sapq.withFKs
		_spec       = sapq.querySpec()
		loadedTypes = [1]bool{
			sapq.withStudentProfile != nil,
		}
	)
	if sapq.withStudentProfile != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, studentacademicprofile.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &StudentAcademicProfile{config: sapq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, sapq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := sapq.withStudentProfile; query != nil {
		ids := make([]xid.ID, 0, len(nodes))
		nodeids := make(map[xid.ID][]*StudentAcademicProfile)
		for i := range nodes {
			if nodes[i].student_profile_academic_profile == nil {
				continue
			}
			fk := *nodes[i].student_profile_academic_profile
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(studentprofile.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "student_profile_academic_profile" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.StudentProfile = n
			}
		}
	}

	return nodes, nil
}

func (sapq *StudentAcademicProfileQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sapq.querySpec()
	_spec.Node.Columns = sapq.fields
	if len(sapq.fields) > 0 {
		_spec.Unique = sapq.unique != nil && *sapq.unique
	}
	return sqlgraph.CountNodes(ctx, sapq.driver, _spec)
}

func (sapq *StudentAcademicProfileQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := sapq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (sapq *StudentAcademicProfileQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   studentacademicprofile.Table,
			Columns: studentacademicprofile.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: studentacademicprofile.FieldID,
			},
		},
		From:   sapq.sql,
		Unique: true,
	}
	if unique := sapq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := sapq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, studentacademicprofile.FieldID)
		for i := range fields {
			if fields[i] != studentacademicprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sapq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sapq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sapq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sapq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sapq *StudentAcademicProfileQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sapq.driver.Dialect())
	t1 := builder.Table(studentacademicprofile.Table)
	columns := sapq.fields
	if len(columns) == 0 {
		columns = studentacademicprofile.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sapq.sql != nil {
		selector = sapq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sapq.unique != nil && *sapq.unique {
		selector.Distinct()
	}
	for _, p := range sapq.predicates {
		p(selector)
	}
	for _, p := range sapq.order {
		p(selector)
	}
	if offset := sapq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sapq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StudentAcademicProfileGroupBy is the group-by builder for StudentAcademicProfile entities.
type StudentAcademicProfileGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sapgb *StudentAcademicProfileGroupBy) Aggregate(fns ...AggregateFunc) *StudentAcademicProfileGroupBy {
	sapgb.fns = append(sapgb.fns, fns...)
	return sapgb
}

// Scan applies the group-by query and scans the result into the given value.
func (sapgb *StudentAcademicProfileGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := sapgb.path(ctx)
	if err != nil {
		return err
	}
	sapgb.sql = query
	return sapgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (sapgb *StudentAcademicProfileGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := sapgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (sapgb *StudentAcademicProfileGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(sapgb.fields) > 1 {
		return nil, errors.New("ent: StudentAcademicProfileGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := sapgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (sapgb *StudentAcademicProfileGroupBy) StringsX(ctx context.Context) []string {
	v, err := sapgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (sapgb *StudentAcademicProfileGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = sapgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{studentacademicprofile.Label}
	default:
		err = fmt.Errorf("ent: StudentAcademicProfileGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (sapgb *StudentAcademicProfileGroupBy) StringX(ctx context.Context) string {
	v, err := sapgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (sapgb *StudentAcademicProfileGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(sapgb.fields) > 1 {
		return nil, errors.New("ent: StudentAcademicProfileGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := sapgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (sapgb *StudentAcademicProfileGroupBy) IntsX(ctx context.Context) []int {
	v, err := sapgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (sapgb *StudentAcademicProfileGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = sapgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{studentacademicprofile.Label}
	default:
		err = fmt.Errorf("ent: StudentAcademicProfileGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (sapgb *StudentAcademicProfileGroupBy) IntX(ctx context.Context) int {
	v, err := sapgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (sapgb *StudentAcademicProfileGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(sapgb.fields) > 1 {
		return nil, errors.New("ent: StudentAcademicProfileGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := sapgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (sapgb *StudentAcademicProfileGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := sapgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (sapgb *StudentAcademicProfileGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = sapgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{studentacademicprofile.Label}
	default:
		err = fmt.Errorf("ent: StudentAcademicProfileGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (sapgb *StudentAcademicProfileGroupBy) Float64X(ctx context.Context) float64 {
	v, err := sapgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (sapgb *StudentAcademicProfileGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(sapgb.fields) > 1 {
		return nil, errors.New("ent: StudentAcademicProfileGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := sapgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (sapgb *StudentAcademicProfileGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := sapgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (sapgb *StudentAcademicProfileGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = sapgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{studentacademicprofile.Label}
	default:
		err = fmt.Errorf("ent: StudentAcademicProfileGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (sapgb *StudentAcademicProfileGroupBy) BoolX(ctx context.Context) bool {
	v, err := sapgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sapgb *StudentAcademicProfileGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range sapgb.fields {
		if !studentacademicprofile.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := sapgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sapgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (sapgb *StudentAcademicProfileGroupBy) sqlQuery() *sql.Selector {
	selector := sapgb.sql.Select()
	aggregation := make([]string, 0, len(sapgb.fns))
	for _, fn := range sapgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(sapgb.fields)+len(sapgb.fns))
		for _, f := range sapgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(sapgb.fields...)...)
}

// StudentAcademicProfileSelect is the builder for selecting fields of StudentAcademicProfile entities.
type StudentAcademicProfileSelect struct {
	*StudentAcademicProfileQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (saps *StudentAcademicProfileSelect) Scan(ctx context.Context, v interface{}) error {
	if err := saps.prepareQuery(ctx); err != nil {
		return err
	}
	saps.sql = saps.StudentAcademicProfileQuery.sqlQuery(ctx)
	return saps.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (saps *StudentAcademicProfileSelect) ScanX(ctx context.Context, v interface{}) {
	if err := saps.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (saps *StudentAcademicProfileSelect) Strings(ctx context.Context) ([]string, error) {
	if len(saps.fields) > 1 {
		return nil, errors.New("ent: StudentAcademicProfileSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := saps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (saps *StudentAcademicProfileSelect) StringsX(ctx context.Context) []string {
	v, err := saps.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (saps *StudentAcademicProfileSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = saps.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{studentacademicprofile.Label}
	default:
		err = fmt.Errorf("ent: StudentAcademicProfileSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (saps *StudentAcademicProfileSelect) StringX(ctx context.Context) string {
	v, err := saps.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (saps *StudentAcademicProfileSelect) Ints(ctx context.Context) ([]int, error) {
	if len(saps.fields) > 1 {
		return nil, errors.New("ent: StudentAcademicProfileSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := saps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (saps *StudentAcademicProfileSelect) IntsX(ctx context.Context) []int {
	v, err := saps.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (saps *StudentAcademicProfileSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = saps.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{studentacademicprofile.Label}
	default:
		err = fmt.Errorf("ent: StudentAcademicProfileSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (saps *StudentAcademicProfileSelect) IntX(ctx context.Context) int {
	v, err := saps.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (saps *StudentAcademicProfileSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(saps.fields) > 1 {
		return nil, errors.New("ent: StudentAcademicProfileSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := saps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (saps *StudentAcademicProfileSelect) Float64sX(ctx context.Context) []float64 {
	v, err := saps.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (saps *StudentAcademicProfileSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = saps.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{studentacademicprofile.Label}
	default:
		err = fmt.Errorf("ent: StudentAcademicProfileSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (saps *StudentAcademicProfileSelect) Float64X(ctx context.Context) float64 {
	v, err := saps.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (saps *StudentAcademicProfileSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(saps.fields) > 1 {
		return nil, errors.New("ent: StudentAcademicProfileSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := saps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (saps *StudentAcademicProfileSelect) BoolsX(ctx context.Context) []bool {
	v, err := saps.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (saps *StudentAcademicProfileSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = saps.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{studentacademicprofile.Label}
	default:
		err = fmt.Errorf("ent: StudentAcademicProfileSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (saps *StudentAcademicProfileSelect) BoolX(ctx context.Context) bool {
	v, err := saps.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (saps *StudentAcademicProfileSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := saps.sql.Query()
	if err := saps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
