// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CollegeProfile is the predicate function for collegeprofile builders.
type CollegeProfile func(*sql.Selector)

// Company is the predicate function for company builders.
type Company func(*sql.Selector)

// JobPost is the predicate function for jobpost builders.
type JobPost func(*sql.Selector)

// StudentAcademicProfile is the predicate function for studentacademicprofile builders.
type StudentAcademicProfile func(*sql.Selector)

// StudentProfile is the predicate function for studentprofile builders.
type StudentProfile func(*sql.Selector)

// StudentWorkProfile is the predicate function for studentworkprofile builders.
type StudentWorkProfile func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
